AWSTemplateFormatVersion: 2010-09-09

Parameters:
  QuickSightIdentityRegion:
    Type: String
    MinLength: 1
    Description: Region where QuickSight identity is configured.
  QuickSightUser:
    Type: String
    MinLength: 1
    Description: User name of QuickSight author/admin from default namespace.

Resources:
  DataSource:
    Type: AWS::QuickSight::DataSource
    Properties:
      Name: !Join [ '', [ 'datasource-' , !Ref 'AWS::AccountId'] ]
      DataSourceId: !Join [ '', [ 'unique-datasource-' , !Ref 'AWS::AccountId'] ]
      AwsAccountId: !Ref 'AWS::AccountId'
      Type: ATHENA
      DataSourceParameters:
        AthenaParameters:
          WorkGroup: primary
      Permissions:
        - Principal: !Join [ '', [ 'arn:aws:quicksight:us-east-1:' , !Ref 'AWS::AccountId', ':user/default/',!Ref 'QuickSightUser' ] ]
          Actions:
            - 'quicksight:UpdateDataSourcePermissions'
            - 'quicksight:DescribeDataSource'
            - 'quicksight:DescribeDataSourcePermissions'
            - 'quicksight:PassDataSource'
            - 'quicksight:UpdateDataSource'
            - 'quicksight:DeleteDataSource'
    
  CostDataSource:
    Type: AWS::QuickSight::DataSource
    Properties:
      Name: !Join [ '', [ 'cost-datasource-' , !Ref 'AWS::AccountId'] ]
      DataSourceId: !Join [ '', [ 'cost-unique-datasource-' , !Ref 'AWS::AccountId'] ]
      AwsAccountId: !Ref 'AWS::AccountId'
      Type: ATHENA
      DataSourceParameters:
        AthenaParameters:
          WorkGroup: primary
      Permissions:
        - Principal: !Join [ '', [ 'arn:aws:quicksight:us-east-1:' , !Ref 'AWS::AccountId', ':user/default/',!Ref 'QuickSightUser' ] ]
          Actions:
            - 'quicksight:UpdateDataSourcePermissions'
            - 'quicksight:DescribeDataSource'
            - 'quicksight:DescribeDataSourcePermissions'
            - 'quicksight:PassDataSource'
            - 'quicksight:UpdateDataSource'
            - 'quicksight:DeleteDataSource'

  DataSet:
    Type: 'AWS::QuickSight::DataSet'
    Properties:
      Name: !Join [ '', [ 'dataset-' , !Ref 'AWS::AccountId'] ]
      DataSetId: !Join [ '', [ 'unique-dataset-' , !Ref 'AWS::AccountId'] ]
      AwsAccountId: !Ref 'AWS::AccountId'
      PhysicalTableMap:
        BackupPhysicalTable:
          CustomSQL:
            Columns:
              - Name: ResourceArn
                Type: STRING
              - Name: ResourceType
                Type: STRING
              - Name: BackupSize
                Type: DECIMAL
              - Name: Department
                Type: STRING
              - Name: Environment
                Type: STRING
            DataSourceArn: !GetAtt DataSource.Arn
            Name: "20"
            SqlQuery: SELECT * FROM "database-774446988871"."20"
      Permissions:
        - Principal: !Join [ '', [ 'arn:aws:quicksight:us-east-1:' , !Ref 'AWS::AccountId', ':user/default/',!Ref 'QuickSightUser' ] ]
          Actions:
            - 'quicksight:UpdateDataSetPermissions'
            - 'quicksight:DescribeDataSet'
            - 'quicksight:DescribeDataSetPermissions'
            - 'quicksight:PassDataSet'
            - 'quicksight:DescribeIngestion'
            - 'quicksight:ListIngestions'
            - 'quicksight:UpdateDataSet'
            - 'quicksight:DeleteDataSet'
            - 'quicksight:CreateIngestion'
            - 'quicksight:CancelIngestion'
      ImportMode: SPICE

  CostDataSet:
    Type: 'AWS::QuickSight::DataSet'
    Properties:
      Name: !Join [ '', [ 'cost-dataset-' , !Ref 'AWS::AccountId'] ]
      DataSetId: !Join [ '', [ 'cost-unique-dataset-' , !Ref 'AWS::AccountId'] ]
      AwsAccountId: !Ref 'AWS::AccountId'
      PhysicalTableMap:
        CostPhysicalTable:
          CustomSQL:
            Columns:
              - Name: Tags
                Type: STRING
              - Name: UnblendedCost
                Type: FLOAT
            DataSourceArn: !GetAtt CostDataSource.Arn
            Name: "20"
            SqlQuery: SELECT * FROM "cost-database-774446988871"."20"
      Permissions:
        - Principal: !Join [ '', [ 'arn:aws:quicksight:us-east-1:' , !Ref 'AWS::AccountId', ':user/default/',!Ref 'QuickSightUser' ] ]
          Actions:
            - 'quicksight:UpdateDataSetPermissions'
            - 'quicksight:DescribeDataSet'
            - 'quicksight:DescribeDataSetPermissions'
            - 'quicksight:PassDataSet'
            - 'quicksight:DescribeIngestion'
            - 'quicksight:ListIngestions'
            - 'quicksight:UpdateDataSet'
            - 'quicksight:DeleteDataSet'
            - 'quicksight:CreateIngestion'
            - 'quicksight:CancelIngestion'
      ImportMode: SPICE

  Template:
      Type: 'AWS::QuickSight::Template'
      Properties:
        TemplateId: !Join [ '', [ 'unique-template-' , !Ref 'AWS::AccountId'] ]
        Name: !Join [ '', [ 'template-' , !Ref 'AWS::AccountId'] ]
        AwsAccountId: !Ref 'AWS::AccountId'
        SourceEntity:
          SourceAnalysis:
            # Arn: !Join [ '', [ 'arn:aws:quicksight:us-east-1:' , !Ref 'AWS::AccountId',':unique-analysis-', !Ref 'AWS::AccountId'] ]
            Arn: !Join [ '', [ 'arn:aws:quicksight:us-east-1:' , !Ref 'AWS::AccountId',':analysis/e19ea927-5534-4c00-837e-06dd196001ed'] ]
            DataSetReferences:
              - DataSetPlaceholder: DataSet
                DataSetArn: !GetAtt DataSet.Arn
              - DataSetPlaceholder: CostDataSet
                DataSetArn: !GetAtt CostDataSet.Arn
        Permissions:
          - Principal: !Join [ '', [ 'arn:aws:quicksight:us-east-1:' , !Ref 'AWS::AccountId', ':user/default/',!Ref 'QuickSightUser' ] ]
            Actions:
              - 'quicksight:DescribeTemplate'
              - 'quicksight:UpdateTemplatePermissions'
              - 'quicksight:DescribeTemplatePermissions'
              - 'quicksight:UpdateTemplateAlias'
              - 'quicksight:DeleteTemplateAlias'
              - 'quicksight:DescribeTemplateAlias'
              - 'quicksight:ListTemplateAliases'
              - 'quicksight:ListTemplates'
              - 'quicksight:CreateTemplateAlias'
              - 'quicksight:DeleteTemplate'
              - 'quicksight:UpdateTemplate'
              - 'quicksight:ListTemplateVersions'
              - 'quicksight:DescribeTemplate'
              - 'quicksight:CreateTemplate'

  Analysis:
    Type: 'AWS::QuickSight::Analysis'
    Properties:
      Name: !Join [ '', [ 'analysis-' , !Ref 'AWS::AccountId'] ]
      AnalysisId: !Join [ '', [ 'unique-analysis-' , !Ref 'AWS::AccountId'] ]
      AwsAccountId: !Ref 'AWS::AccountId'
      SourceEntity:
        SourceTemplate:
          Arn: !GetAtt Template.Arn
          DataSetReferences:
          - DataSetPlaceholder: DataSet
            DataSetArn: !GetAtt DataSet.Arn
          - DataSetPlaceholder: CostDataSet
            DataSetArn: !GetAtt CostDataSet.Arn
      Permissions:
        - Principal: !Join [ '', [ 'arn:aws:quicksight:us-east-1:' , !Ref 'AWS::AccountId', ':user/default/',!Ref 'QuickSightUser' ] ]
          Actions:
            - 'quicksight:RestoreAnalysis'
            - 'quicksight:UpdateAnalysisPermissions'
            - 'quicksight:DeleteAnalysis'
            - 'quicksight:DescribeAnalysisPermissions'
            - 'quicksight:QueryAnalysis'
            - 'quicksight:DescribeAnalysis'
            - 'quicksight:UpdateAnalysis'
